In [ ]:
import math
import statistics
import numpy as np
from scipy import linalg

In [ ]:
x=7.5

print("Floor:",math.floor(x))
print("Ceil:",math.ceil(x))
print("sqrt:",math.sqrt(16))
print("isqrt:",math.isqrt(16))
print("GCD:",math.gcd(60,48))

Floor: 7
Ceil: 8
sqrt: 4.0
isqrt: 4
GCD: 12


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])

print("ndim:",arr.ndim)
print("shape:",arr.shape)
print("size:",arr.size)

print("sum:",arr.sum())
print("mean:",arr.mean())
print("sort:",np.sort(arr,axis=None))
print("sin:",np.sin(arr))

ndim: 2
shape: (2, 3)
size: 6
sum: 21
mean: 3.5
sort: [1 2 3 4 5 6]
sin: [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [ ]:
A=np.array([[1,2],[2,5]])

det=linalg.det(A)
print("det:",det)

eigvals, eigvecs = linalg.eig(A)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

det: 1.0
Eigenvalues: [0.17157288+0.j 5.82842712+0.j]
Eigenvectors:
 [[-0.92387953 -0.38268343]
 [ 0.38268343 -0.92387953]]


In [ ]:
lst = [1, 2, 3, 4, 5, 6]

arr1d = np.array(lst)
print("1D Array:\n",arr1d)

arr2d = arr1d.reshape(2, 3)
print("2D Array:\n", arr2d)

arr3d = arr1d.reshape(2, 1, 3)
print("3D Array:\n", arr3d)

1D Array:
 [1 2 3 4 5 6]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2 3]]

 [[4 5 6]]]


In [ ]:
zeros = np.zeros((2,2))
ones = np.ones((3,3))
rand = np.random.rand(2,3)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Random:\n", rand)

Zeros:
 [[0. 0.]
 [0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Random:
 [[0.69482514 0.56987285 0.42778494]
 [0.08648975 0.42515695 0.56901509]]


In [ ]:
B = np.array([[5, 6], [7, 8]])
det_B = linalg.det(B)
print("Determinant of B:", det_B)

Determinant of B: -2.0000000000000036


In [ ]:
eigvals_B, eigvecs_B = linalg.eig(B)
print("Eigenvalues of B:\n", eigvals_B)
print("Eigenvectors of B:\n", eigvecs_B)

Eigenvalues of B:
 [-0.15206735+0.j 13.15206735+0.j]
Eigenvectors of B:
 [[-0.75868086 -0.59276441]
 [ 0.65146248 -0.80537591]]


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
ser = pd.Series([10, 20, 30, 40, 50])
print("Series:\n", ser)

Series:
 0    10
1    20
2    30
3    40
4    50
dtype: int64


In [ ]:
print("Index:", ser.index)
print("Values:", ser.values)

Index: RangeIndex(start=0, stop=5, step=1)
Values: [10 20 30 40 50]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print("NumPy Array:\n", arr)
print("Pandas Series:\n", ser)

NumPy Array:
 [10 20 30 40 50]
Pandas Series:
 0    10
1    20
2    30
3    40
4    50
dtype: int64


In [ ]:
grades = pd.Series([85, 90, 95], index=['Math', 'Science', 'English'])
print("Series with custom indices:\n", grades)

Series with custom indices:
 Math       85
Science    90
English    95
dtype: int64


In [ ]:
print("Math Grade:", grades['Math'])

Math Grade: 85


In [ ]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df = pd.read_csv(url)

print("Head of DataFrame:\n", df.head())

Head of DataFrame:
    sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [ ]:
import pandas as pd

data_dict = {
    'Name': ['Abi', 'Sam', 'Jess'],
    'Age': [21, 22, 23],
    'Marks': [85, 90, 95]
}

df = pd.DataFrame(data_dict)
print("DataFrame from dict:\n", df)

data_list = [
    ['Abi', 21, 85],
    ['Sam', 22, 90],
    ['Jess', 23, 95]
]

df2 = pd.DataFrame(data_list, columns=['Name', 'Age', 'Marks'])
print("\nDataFrame from list:\n", df2)

DataFrame from dict:
    Name  Age  Marks
0   Abi   21     85
1   Sam   22     90
2  Jess   23     95

DataFrame from list:
    Name  Age  Marks
0   Abi   21     85
1   Sam   22     90
2  Jess   23     95


In [ ]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df_csv = pd.read_csv(url)

print("CSV DataFrame:\n", df_csv.head())

CSV DataFrame:
    sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [ ]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()

print("Iris keys:", iris.keys())
df_iris = pd.DataFrame(iris.data, columns=iris.feature_names)
df_iris['target'] = iris.target

print("\nIris DataFrame:\n", df_iris.head())

from sklearn.datasets import load_diabetes

diabetes = load_diabetes()
df_diabetes = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
df_diabetes['target'] = diabetes.target

print("\nDiabetes DataFrame:\n", df_diabetes.head())

Iris keys: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

Iris DataFrame:
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  

Diabetes DataFrame:
         age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.0323